version: '3.1'

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_DB}
      - MONGO_INITDB_ROOT_PASSWORD=${PASS_DB}
