test:
	docker compose -f docker-compose.yml -f docker-compose.yml -p mern-zustand-auth-test up -d 
dev:
	docker compose -f docker-compose.yml up -d 

test-down: 
	docker compose -p mern-zustand-auth-test down 
dev-down: 
	docker compose down 